# This docker-compose file may not work, for reference, dev or test purposes.
# Modify it if needed.
version: "3.7"
services:
  privacyidea:
    image: ghcr.io/invizus/privacyidea:v0.1.2
    container_name: privacyidea
    ports:
      - "8080:8080"
#      - "8443:8443"
#      Image is built to expose port 8443, but for test purposes if you are not
#      using any TLS certs, change Dockerfile to expose port 8080.
    environment:
      - PRIVACYIDEA_CONFIGFILE=/etc2/pi.cfg
      - DATABASE_URL="mysql+pymysql://pi:password@db:3306/pi"
      - PI_LOGFILE=/var/log/privacyidea.log
      - SECRET_KEY="<generate>"
    volumes:
      - ./config:/etc2
    restart: always
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example1
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
