---
apiVersion: v1
kind: Namespace
metadata:
  name: privacyidea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privacyidea
  labels:
    app: privacyidea
  namespace: privacyidea
spec:
  selector:
    matchLabels:
      app: privacyidea
  template:
    metadata:
      labels:
        app: privacyidea
    spec:
      containers:
      - name: app
        image: ghcr.io/invizus/privacyidea:v0.1.2

